server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: flink-manager
          uri: ${FLINK_MANAGER_URL:http://localhost:8081}
          predicates:
            - Path=/api/**
        - id: flink-manager-docs
          uri: ${FLINK_MANAGER_URL:http://localhost:8081}
          predicates:
            - Path=/flink-manager/v3/api-docs
          filters:
            - RewritePath=/flink-manager/v3/api-docs, /v3/api-docs
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"

springdoc:
  swagger-ui:
    urls:
      - name: api-gateway
        url: /v3/api-docs
      - name: flink-manager
        url: /flink-manager/v3/api-docs

app:
  security:
    user:
      name: ${SECURITY_USER_NAME:user}
      password: ${SECURITY_USER_PASSWORD:password}
